# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{opengraph}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new("~> 2.4") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gram"]
  s.date = %q{2015-09-01}
  s.description = %q{A very simple Ruby library for parsing Open Graph prototocol information from websites. See http://opengraphprotocol.org for more information.}
  s.email = %q{g@dented.io}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rspec",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/opengraph.rb",
     "opengraph.gemspec",
     "spec/examples/partial.html",
     "spec/examples/rottentomatoes.html",
     "spec/opengraph_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/dented/opengraph}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{2.4.8}
  s.summary = %q{A very simple Ruby library for parsing Open Graph prototocol information from websites.}
  s.test_files = [
    "spec/opengraph_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('2.4.8') then
      s.add_runtime_dependency(%q<hashie>, ["~> 3.3"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.6"])
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.8"])
      s.add_development_dependency(%q<rspec>, ["~> 3.3"])
      s.add_development_dependency(%q<webmock>, ["~> 1.20"])
    else
      s.add_dependency(%q<hashie>, ["~> 3.3"])
      s.add_dependency(%q<nokogiri>, ["~> 1.4"])
      s.add_dependency(%q<rest-client>, ["~> 1.6"])
      s.add_development_dependency(%q<rspec>, ["~> 3.3"])
      s.add_development_dependency(%q<webmock>, ["~> 1.20"])
    end
  else
    s.add_dependency(%q<hashie>, ["~> 3.3"])
    s.add_dependency(%q<nokogiri>, ["~> 1.4"])
    s.add_dependency(%q<rest-client>, ["~> 1.6"])
    s.add_development_dependency(%q<rspec>, ["~> 3.3"])
    s.add_development_dependency(%q<webmock>, ["~> 1.20"])
  end
end
